### ISSUE TITLE
[Tracker] Known Issues

### ISSUE THREAD

**Issue by vifino** [carbonsrv/carbon#6]
There are a few known issues with Carbon which are yet to be fixed. This can also be seen as a TODO list.

* [ ] Lua Issues
  * [ ] Binding Values is buggy
    * [ ] Buggy in regards to binding Go Chans and similar non-lua stuff. Binding one Chan seems to work, but two... Nope!
  * [ ] Better Errors
    * [ ] Better Error checking in wrapper functions, tells you if you do something wrong.
    * [ ] Better Syntax Errors, panic() isn't very pleasing...
* [ ] Proper Wiki/Docs, documenting...
  * [ ] Functions/APIs
  * [ ] Architecture
  * [ ] Inner Workings
  * [ ] Compatibility/Porting Guide
